export const DataLocalidades = [
    { name: "Formosa" },
    { name: "El Colorado" },
    { name: "Clorinda" },
    { name: "Laguna Blanca" },
    { name: "Villa General Manuel Belgrano" },
  ];

export const DataBarrios = {
    "Formosa": [
      // { name: "12 DE OCTUBRE", houses: 526 },
      // { name: "2 DE ABRIL", houses: 1022 },
      // { name: "BARRIO MILITAR", houses: 119 },
      // { name: "OBRERO", houses: 1401 },
      // { name: "BARRIO VIAL", houses: 958 },
      // { name: "DON BOSCO", houses: 1606 },
      // { name: "EL MISTOL", houses: 98 },
      // { name: "EL RESGUARDO", houses: 513 },
      // { name: "MANUEL BELGRANO", houses: 71 },
      // { name: "EMILIO TOMAS", houses: 340 },
      // { name: "EVA PERÓN", houses: 2200 },
      { name: "GUADALUPE", houses: 1435 },
      // { name: "INDEPENDENCIA", houses: 1462 },
      // { name: "J.F. KENNEDY", houses: 90 },
      // { name: "JUAN D. PERÓN", houses: 1143 },
      // { name: "LA FLORESTA", houses: 831 },
      // { name: "LAS DELICIAS", houses: 213 },
      // { name: "LIBORSI", houses: 714 },
      { name: "MARIANO MORENO", houses: 1636 },
      // { name: "NANQOM", houses: 433 },
      { name: "SAN AGUSTÍN", houses: 780 },
      // { name: "SAN FRANCISCO", houses: 2222 },
      // { name: "SAN JOSÉ OBRERO", houses: 741 },
      { name: "SAN MARTÍN", houses: 3814 },
      // { name: "SAN MIGUEL", houses: 1333 },
      // { name: "SAN PEDRO", houses: 743 },
      // { name: "SANTA ROSA", houses: 421 },
      // { name: "SIMÓN BOLIVAR", houses: 2161 },
      // { name: "VENEZUELA", houses: 619 },
      // { name: "VILLA DEL ROSARIO", houses: 1106 },
      // { name: "VILLA HERMOSA", houses: 505 },
      // { name: "VILLA LA PILAR", houses: 954 },
      // { name: "VILLA LOURDES", houses: 1244 },
      // { name: "VIRGEN DE LUJÁN", houses: 316 },
      // { name: "LA ESPERANZA", houses: 180 },
      // { name: "7 DE MAYO", houses: 368 },
      // { name: "ANTENOR GAUNA", houses: 1069 },
      // { name: "1° DE MAYO", houses: 184 },
      // { name: "EL PORVENIR", houses: 352 },
      // { name: "BERNARDINO RIVADAVIA", houses: 890 },
      // { name: "VIRGEN DE ITATÍ", houses: 782 },
      // { name: "PARQUE INDUSTRIAL", houses: 27 },
      // { name: "SAN JUAN BAUTISTA", houses: 671 },
      // { name: "16 DE JULIO", houses: 73 },
      // { name: "SAG. CORAZÓN DE MARÍA", houses: 100 },
      // { name: "ARTURO ILLIA", houses: 935 },
      // { name: "HIPÓLITO IRIGOYEN", houses: 193 },
      // { name: "SAN CAYETANO", houses: 217 },
      // { name: "FACUNDO QUIROGA", houses: 82 },
      // { name: "SAN ANDRES", houses: 177 },
      // { name: "SANTA LUCÍA", houses: 101 },
      // { name: "LA VIRGEN NIÑA", houses: 184 },
      // { name: "17 DE OCTUBRE", houses: 123 },
      // { name: "LIBERTAD", houses: 129 },
      // { name: "ISLAS MALVINAS", houses: 197 },
      // { name: "COLLUCCIO", houses: 443 },
      // { name: "SAN ISIDRO LABRADOR", houses: 396 },
      // { name: "ROBERTO SOTELO", houses: 133 },
      // { name: "8 DE MARZO", houses: 226 },
      // { name: "CO.VI.FOL.", houses: 124 },
      // { name: "FONTANA", houses: 1232 },
      // { name: "SOLANO LIMA", houses: 217 },
      // { name: "LA ESTRELLA", houses: 53 },
      // { name: "20 de JULIO", houses: 225 },
      // { name: "REPÚBLICA ARGENTINA", houses: 1895 },
      // { name: "8 DE OCTUBRE", houses: 344 },
      // { name: "EL QUEBRANTO", houses: 152 },
      // { name: "EL QUEBRACHITO", houses: 450 },
      // { name: "EL PALOMAR", houses: 493 },
      // { name: "STELLA MARIS", houses: 216 },
      // { name: "LOS INMIGRANTES", houses: 112 },
      // { name: "LAS ORQUIDEAS", houses: 275 },
      // { name: "Dr. RICARDO BALBÍN", houses: 170 },
      // { name: "SAN JUAN", houses: 316 },
      // { name: "SAN ANTONIO", houses: 454 },
      // { name: "PARQUE URBANO", houses: 522 },
      // { name: "ARTURO ILLIA II", houses: 670 },
      // { name: "YAPEYÚ", houses: 536 },
      // { name: "8 DE OCTUBRE BIS", houses: 234 },
      // { name: "CARACOLITO", houses: 278 },
      // { name: "CONO SUR", houses: 182 },
      // { name: "EL PALMAR", houses: 268 },
      // { name: "EL PUCÚ", houses: 321 },
      // { name: "EL TIMBÓ I", houses: 156 },
      // { name: "EL TIMBÓ II", houses: 299 },
      // { name: "EVITA", houses: 205 },
      // { name: "FEDERACIÓN", houses: 221 },
      // { name: "FLEMING", houses: 169 },
      // { name: "GUAYAIBÍ", houses: 304 },
      // { name: "ITATÍ I", houses: 150 },
      { name: "ITATÍ II", houses: 277 },
      // { name: "JUAN MANUEL DE ROSAS", houses: 189 },
      // { name: "LA PAZ", houses: 253 },
      // { name: "MALVINAS", houses: 212 },
      // { name: "NUEVA FORMOSA", houses: 184 },
      // { name: "NUEVA POMPEYA", houses: 322 },
      // { name: "PARQUE URBANO I", houses: 305 },
      // { name: "PARQUE URBANO II", houses: 185 },
      // { name: "SAN PÍO X", houses: 257 },
      // { name: "SAN JOSÉ OBRERO", houses: 311 },
      // { name: "SARMIENTO", houses: 278 },
      // { name: "URUNDAY", houses: 226 },
      // { name: "VILLA JARDÍN", houses: 300 },
      // { name: "VIRGEN DEL CARMEN", houses: 245 },
      // { name: "VIRGEN NUESTRA SEÑORA DEL PILAR", houses: 178 },
      // { name: "LOTE 4", houses: 158 },
      // { name: "LUJAN", houses: 274 },
      // { name: "ZONA RURAL", houses: 783 },
    ],
    "El Colorado": [
      { name: "CENTRO", houses: 287 },
      { name: "OBRERO", houses: 384 },
      { name: "SAN MIGUEL", houses: 431 },
      { name: "SAN FRANCISCO", houses: 308 },
    ],
    "Villa General Manuel Belgrano": [
      { name: "CENTRO", houses: 391 },
      { name: "40 VIVIENDAS", houses: 492 },
      { name: "12 DE OCTUBRE", houses: 359 },
    ],
    "Laguna Blanca": [
      { name: "CENTRO", houses: 406 },
      { name: "SAN JUAN", houses: 481 },
      { name: "SAN MIGUEL", houses: 532 },
      { name: "BELGRANO", houses: 357 },
    ],
    "Clorinda": [
      { name: "CENTRO", houses: 512 },
      { name: "25 DE MAYO", houses: 401 },
      { name: "LIBERTAD", houses: 535 },
      { name: "PORTEÑO NORTE", houses: 296 },
      { name: "240 VIVIENDAS", houses: 452 },
    ],
  };

  export const DataLocalidadesRurales = [
    { name: "Potrero Norte" },
    { name: "Colonia La Primavera" },
    { name: "Colonia Ituzaingo" },
    { name: "Colonia Sudamericana" },
    { name: "Colonia El Progreso" },
    { name: "Riacho He-He" },
    { name: "El Guajo" },
    { name: "El Ceibal" },
    { name: "Alto Alegre" },
    { name: "El Corralito" },
    { name: "Loma Senes" },
    { name: "El Potrillo" },
    { name: "Colonia El Dorado" },
    { name: "El Recreo" },
    { name: "Las Cañitas" },
  ];

export const DataBarriosRurales = {
  "Potrero Norte": [
    {name: "San Martín", houses: 19},   
    {name: "Sarmiento", houses: 13}, 
    {name: "Independencia", houses: 11},
  ],
  "Colonia La Primavera": [
    {name: "Alberdi", houses: 9},      
    {name: "Santa Rosa", houses: 4},   
    {name: "Independencia", houses: 21},
  ],
  "Colonia Ituzaingo": [
    {name: "Independencia", houses: 14},      
    {name: "San Fernando", houses: 14},   
    {name: "San Juan", houses: 18},
  ],
  "Colonia Sudamericana": [
    {name: "San Martín", houses: 25},      
    {name: "Alberdi", houses: 3},   
    {name: "San Nicolás", houses: 7},
  ],
  "Colonia El Progreso": [
    {name: "9 de Julio", houses: 12},      
    {name: "Güemes", houses: 24},   
    {name: "Sarmiento", houses: 18},
  ],
  "Riacho He-He": [
    {name: "Sarmiento", houses: 11},      
    {name: "9 de Julio", houses: 14},   
    {name: "San José", houses: 22},
  ],
  "El Guajo": [
    {name: "Güemes", houses: 14},      
    {name: "San Cayetano", houses: 19},   
    {name: "Villa Pueyrredón", houses: 12},
  ],
  "El Ceibal": [
    {name: "San Antonio", houses: 10},      
    {name: "Belgrano", houses: 10},   
    {name: "San Lorenzo", houses: 24},
  ],
  "Alto Alegre": [
    {name: "San Martín", houses: 23},      
    {name: "San Cayetano", houses: 11},   
    {name: "Belgrano", houses: 8},
  ],
  "El Corralito": [
    {name: "San Pedro", houses: 6},      
    {name: "San Rafael", houses: 17},   
    {name: "San Roque", houses: 24},
  ],
  "Loma Senes": [
    {name: "San Miguel", houses: 11},      
    {name: "Alberdi", houses: 13},   
    {name: "Villa Mitre", houses: 10},
  ],
  "El Potrillo": [
    {name: "Alberdi", houses: 14},    
    {name: "9 de Julio", houses: 14},   
    {name: "San Agustín", houses: 19},
  ],
  "Colonia El Dorado": [
    {name: "San Cayetano", houses: 16},     
    {name: "9 de Julio", houses: 23},   
    {name: "20 de Febrero", houses: 4},
  ],
  "El Recreo": [
    {name: "San Ignacio", houses: 23},      
    {name: "San Cayetano", houses: 11},   
    {name: "20 de Febrero", houses: 8},
  ],
  "Las Cañitas": [
    {name: "Sarmiento", houses: 14},      
    {name: "San Isidro", houses: 19},   
    {name: "Belgrano", houses: 12},
  ],
}

export const DataCalles = {
  "Formosa": {
    "GUADALUPE": [
      "Avenida Antártida Argentina",
      "Base Marambio",
      "Corrientes",
      "Fuerza Aérea Argentina",
      "Juan José Silva",
      "Juan Manuel de Rosas",
      "Maipú",
      "Pasaje Caracol",
      "Policía de los Territorios Nacionales"
    ],
    "MARIANO MORENO": [
      "Salta",
      "Hipolito Yrigoyen",
      "Fotheringham",
      "Velez Sarsfield",
      "Pueyrredon",
      "Larrea",
      "Juan Bautista Alberdi",
      "Manuel Alberti"
    ],
    "ITATÍ II": [
      "Martin Fierro",
      "Masferrer",
      "Soardella",
      "16 de Julio",
      "Coronel Bogado",
      "Avenida Italia",
      "Alicia Moreau de Justo"
    ],
    "SAN AGUSTÍN": [
      "Marcial Rojas",
      "Soldado Torales",
      "Masaferro",
      "Tomás Parkinson",
      "Soldado Arrieta",
      "Carlos Girola",
      "Santa Barbara",
      "Miguel Gutierrez"
    ],
    "SAN MARTÍN": [
      "Manuel Belgrano",
      "Rivadavia",
      "Salta",
      "Ayacucho",
      "Paraguay",
      "Pringles",
      "Brandsen",
      "España",
      "San Martin",
      "Saavedra"
    ],
  },
  "El Colorado": {
    "CENTRO": [
      "9 de Julio",
      "Salta",
      "Hipolito Yrigoyen",
      "Bartolomé Mitre",
      "Juan Manuel de Rosas",
    ], 
    "OBRERO": [
      "Guillermo Brown",
      "Juan Bacik",
      "Mendoza",
      "Nicolas Barrios",
      "Cirilo Pourcel",
    ],
    "SAN MIGUEL": [
      "Fontana",
      "Güemes",
      "Juan José Paso",
      "Larralde",
      "San Juan",
    ],
    "SAN FRANCISCO": [
      "Avenida Nestor Kirchner",
      "Santa Fe",
      "Juan Bacik",
      "Cirilo Pourcel",
      "Mendoza",
    ]
  },
  "Clorinda": {
    "CENTRO": [
      "Guerreto",
      "Potosí",
      "Sarmiento",
      "Rivadavia",
      "Los Andes",
    ],
    "25 DE MAYO": [
      "San Luís",
      "General Martín Güemes",
      "Neuquén",
      "Buenos Aires",
      "Paraguay",
    ],
    "LIBERTAD": [
      "Las Americas",
      "Manuel Dorrego",
      "Roberto Américo Paleari",
      "Juan Facundo Quiroga",
      "Santisima Trinidad",
    ],
    "PORTEÑO NORTE": [
      "Franciscanos",
      "Tacuarí",
      "Larrea",
      "Santa Fe",
      "Mendoza",
    ],
    "240 VIVIENDAS": [
      "Jose María Uriburu",
      "Pedro Ferré",
      "Avenida Francisco Bogarin",
      "Oficial Vera",
      "Avenida Juan Domingo Perón",
    ],
  },
  "Villa General Manuel Belgrano": {
    "CENTRO": [
      "Río Negro",
      "Avenida Perú",
      "Misiones",
      "Fortín Leyes",
    ],
    "40 VIVIENDAS": [
      "Belgrano Formosa",
      "Fortín Lugones",
      "Comandante Fontana",
      "Fotherimgham",
    ],
    "12 DE OCTUBRE": [
      "Río Negro",
      "Sarmiento",
      "Zamparo",
      "Avenida Perú",
    ],
  },
  "Laguna Blanca": {
    "CENTRO": [
      "Avenida Paseo Colón",
      "Avellaneda",
      "Alfonzo",
      "Saavedra",
    ],
    "SAN JUAN": [
      "Maipú",
      "Cesar Villalba",
      "Comandante Fontana",
      "2 de Abril",
    ],
    "SAN MIGUEL": [
      "Pueyrredón",
      "Paraguay",
      "Belgrano",
      "Avenida San Martin",
    ],
    "BELGRANO": [
      "Avenida 25 de Mayo",
      "Güemes",
      "Rivadavia",
      "Alem",
    ],
  }
}

export const DataCallesRurales = {
  "Potrero Norte": [
    "San Martín",   
    "Belgrano"
  ],
  "Colonia La Primavera": [    
    "Rivadavia",   
    "Independencia",
  ],
  "Colonia Ituzaingo": [    
    "25 de Mayo",   
    "9 de Julio",
  ],
  "Colonia Sudamericana": [
    "San Martín",   
    "Belgrano"
  ],
  "Colonia El Progreso": [
    "San Martín",   
    "Belgrano"
  ],
  "Riacho He-He": [
    "25 de Mayo",   
    "9 de Julio",
  ],
  "El Guajo": [
    "Rivadavia",   
    "Independencia",
  ],
  "El Ceibal": [
    "25 de Mayo",   
    "9 de Julio",
  ],
  "Alto Alegre": [
    "San Martín",   
    "Belgrano"
  ],
  "El Corralito": [     
    "San Rafael",   
    "San Roque",
  ],
  "Loma Senes": [
    "25 de Mayo",   
    "9 de Julio",  
    "Mitre",
  ],
  "El Potrillo": [
    "San Rafael",   
    "San Roque",
  ],
  "Colonia El Dorado": [
    "9 de Julio",  
    "Mitre",
  ],
  "El Recreo": [
    "Rivadavia",   
    "Independencia",
  ],
  "Las Cañitas": [
    "San Martín",   
    "Belgrano"
  ],
}